services:
  - type: web
    name: digischool-backend
    env: docker
    plan: free # Change to starter if RAM > 512MB is needed
    region: frankfurt # Or your preferred region
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        fromDatabase:
          name: digischool-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: digischool-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: digischool-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JPA_DDL_AUTO
        value: update

databases:
  - name: digischool-db
    plan: free # Free for 90 days on Render
    databaseName: digischool
    user: digischool
