services:
  - type: web
    name: digischool-backend
    env: docker
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: digischool-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: digischool-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: digischool-db
          property: databaseName
      - key: DB_USERNAME
        fromDatabase:
          name: digischool-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: digischool-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JPA_DDL_AUTO
        value: update

databases:
  - name: digischool-db
    plan: free
    databaseName: digischool_ak4h
    user: digischool
    region: oregon
